
GET http://localhost:3000/api/registeredusers
Accept: application/json

###

PUT http://localhost:3000/bulkregister
Content-Type: application/json

{"users": [
{"first": "Alok","last": "Joshi"} ,
{"first": "Sadhna","last": "Joshi"} ,
{"first": "Steven","last": "Tinling"} ,
{"first": "Nony","last": "Bernal"} ,
{"first": "David","last": "Kennedy"} ,
{"first": "Scott","last": "Miller"}, 
{"first": "Laura","last": "Miller"}, 
{"first": "Elizabeth","last": "Silvius"} ,
{"first": "Doreen","last": "Grant"} ,
{"first": "Bruce","last": "Thompson"},
{"first": "Gloria","last": "Harrison"},
{"first": "Jan","last": "Geldreich"} ,
{"first": "Theo","last": "Palmer"} ,
{"first": "Linda","last": "Pearce"} ,
{"first": "Kathy","last": "Kulsic"} ,
{"first": "Chris","last": "Clautice"} ,
{"first": "Bob","last": "Ritzau"} ,
{"first": "Mary Ann","last": "Braden"}, 
{"first": "James","last": "Tanner"} ,
{"first": "James","last": "Borcuk"} ,
{"first": "Alma","last": "Borcuk"} ,
{"first": "George","last": "Pooley"} ,
{"first": "Carma","last": "Pooley"} ,
{"first": "Leo","last": "Harrison"},
{"first": "Chris","last": "Marin"},
{"first": "Celine","last": "Butler"},
{"first": "Diane","last": "Marsh"},
{"first": "Elliott","last": "Meltzer"},
{"first": "Rober","last": "Davis"},
{"first": "Virginia","last": "Devoe"},
{"first": "Emoke","last": "Gasper"},
{"first": "David","last": "Brown"},
{"first": "Kitty","last": "Moon"},
{"first": "Sharon","last": "Neiman"},
{"first": "Anna","last": "Souza"},
{"first": "Gonzalo","last": "Souza"},
{"first": "Paul","last": "Caslavka"},
{"first": "Clark","last": "Dupont"}
]}

### This should fail because alok2 username already exists
PUT http://localhost:3000/register
Content-Type: application/json

{
  "first": "Alok",
  "last": "Joshi",
  "username": "alokj"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "alokj",
  "password": "sadalo2211"
}
###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "alok2",
  "password": "alok40"
}

###

DELETE http://localhost:3000/api/playerdata/1
# Content-Type: application/json

# {
#   "username": "alok2",
#   "password": "alok40"
# }

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "alokj",
  "password": "alok2"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "mary annb",
  "password": "mary ann19"
}

###

POST http://localhost:3000/changePassword
Content-Type: application/json

{
  "username": "abc",
  "oldPassword": "def",
  "newPassword": "newdef"
} 
###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "sadhna",
  "password": "Sadhna2"
} 
###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "steven",
  "password": "Steven110"
} 
###
GET http://localhost:3000/api/registeredusers
Accept: application/json
###
POST http://localhost:3000/changePassword
Content-Type: application/json

{
  "username": "steven",
  "oldPassword": "Steven110",   
  "newPassword": "StevenTinling"
}
###
post http://localhost:3000/login
Content-Type: application/json

{
  "username": "steven",
  "password": "StevenTinling"
} 
###
post http://localhost:3000/isadmin
Content-Type: application/json

{
  "userId": 110
}

###
GET http://localhost:3000/mixofmembersandnonmembers
Accept: application/json

###
GET http://localhost:3000/bridgeterms
Accept: application/json
###

get http://localhost:3000/isinvalidbridgeterm/double

###
get http://localhost:3000/isinvalidbridgeterm/1430

###
get http://localhost:3000/isinvalidbridgeterm/'1430'

###

get http://localhost:3000/isinvalidbridgeterm/14 Card Trump fit

###

get http://localhost:3000/isinvalidbridgeterm/opening bid

###

put http://localhost:3000/checknonmembers
Content-Type: application/json

{
  "nonmembers": ["Amy","Leo"]
}
###
put http://localhost:3000/checknonmembers
Content-Type: application/json

{
  "nonmembers": ["Alok","Leo"]
}

###
put http://localhost:3000/checknonmembers
Content-Type: application/json

{
  "nonmembers": ["Amy","Trent"]
}
###

put http://localhost:3000/checknonmembers
Content-Type: application/json

{
  "nonmembers": ["Sadhna","Alok"]
}
###

put http://localhost:3000/checkfullnameandphone
Content-Type: application/json

{
  "fullname": "sadhna joshi",
  "phone": "909-224-4956"
}
###

put http://localhost:3000/checkfullnameandphone
Content-Type: application/json

{
  "fullname": "adhna joshi"
}
###

get http://localhost:3000/api/playerdata

###
GET http://localhost:3000/get-session-id
Accept: application/json  

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "johnm",
  "password": "john41"
}
###

GET http://localhost:3000/api/attendance/t1
Accept: application/json
###